### ISSUE TITLE
Automatically generate CHANGELOG.md

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#118]
Keeping changelog up-to-date is boring. We could do it automatically like in [Mockito](https://github.com/mockito/mockito/blob/master/doc/release-notes/official.md) - Szczepan plains to release [it](https://github.com/mockito/mockito/tree/master/buildSrc/src/main/groovy/org/mockito/release) as a separate project - probably could be reused.

**Comment by nurkiewicz** [comment]
I just noticed cool new feature of GitHub: https://github.com/4finance/micro-infra-spring/releases - releases page. Basically for each tag we can add arbitrary Markdown notes. There is an [API for that](https://developer.github.com/v3/repos/releases/), so we can automate e.g. adding changelist there, rather than in raw `CHANGELOG.md` file.

**Comment by nurkiewicz** [comment]
https://github.com/4finance/micro-common-release/issues/8 should be implemented as well with this issue.

**Comment by marcingrzejszczak** [comment]
We no longer support CHANGELOG.MD
