### ISSUE TITLE
Dependency graph between micro-infra components

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#120]

**Comment by nurkiewicz** [comment]
Maintaining this diagram has cost. Actually after https://github.com/4finance/micro-infra-spring/issues/132 I believe we no longer need such graph anymore (?) It was meant to simplify release process, which will no longer be that much of a problem. Of course it's useful, but since all modules are now in one project, it's easier to find inter-dependencies. WDYT?

**Comment by mchmielarz** [comment]
Exactly, the diagram is not needed any more after merging everything into single project.
