### ISSUE TITLE
500 response from /api-docs for gui based aps

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/micro-infra-spring#165]
Given a boot-microservice-gui based application
when I go to swagger
then upon fetching of .../api-docs I receive 500

example:
https://github.com/microhackathon-2015-01-Riga/ClientService

**Comment by nurkiewicz** [comment]
Not a bug, issue was caused by casbah library included in https://github.com/microhackathon-2015-01-Riga/ClientService/commit/73f089f8372a23785ae0f3c95c6def603ed6dc09#diff-c197962302397baf3a4cc36463dce5eaR132 resulting in Scala 2.11 on CLASSPATH, while Swagger requires 2.10. Yes, it does matter.

See: https://github.com/microhackathon-2015-01-Riga/ClientService/pull/1.
