### ISSUE TITLE
`MvcWiremockIntegrationSpec.stubInteraction` is not working for `ServiceRestClient.forService`

### ISSUE THREAD

**Issue by mariuszs** [4finance/micro-infra-spring#171]
Interactions recorded with `MvcWiremockIntegrationSpec.stubInteraction(MappingBuilder, ResponseDefinitionBuilder)` are not applied to wiremock server when stub-runner and stub-definiton are used. By design `ServiceRestClient.forService` is using stub-runner wiremock server, and `ServiceRestClient.forExternalService` is using mvc wiremock server. In the end it is impossible to add test specific interactions to zookeper enabled service test.

**Comment by marcingrzejszczak** [comment]
Yes - that has been done on purpose. stubInteraction works only for external servers and those "special cases" should end up in a stub.

**Comment by mariuszs** [comment]
This is not documented.

What if I want test `POST` to one url, for example `/foo` and want to test different responses: `200`, `404`, `500` etc. How can I configure this in `stub-definitions`?

**Comment by marcingrzejszczak** [comment]
The idea of stub definitions and consumer driven contract in our opinion works like this and we're writing about this in multiple places. We don't want people to manually stub collaborators in their code because that will not let us test the validity of that stubbing.

You can do that basing on different bodies or scenarios. For instance for that name of a client will you get a timeout, for another you will get sth else. You have quite a few possibilities of tweaking the input to get the proper output.

If that is not satisfactory for you can ran tests with taking scenarios into account - please check out Wiremock documentation if you don't know this notion - http://wiremock.org/stateful-behaviour.html.

Does it answer you question?

**Comment by mariuszs** [comment]
Yes, but I cannot agree with you. 

I read about Stateful Behaviour, but I have stateless behaviour defined and dont want to add constraint for test order execution (@Stepwise). Your solution looks like hack.

**Comment by mariuszs** [comment]
BTW, `stubInteraction` can access existing wiremock server endpoint and add additional behaviours instead of using second wiremock server.

**Comment by marcingrzejszczak** [comment]
I only mentioned stateful behaviour - what we do in our projects is that for certain data we test certain behaviour like I wrote before. We prepare some data that will answer in some ways. That's actually not a hack but it's quite normal. I don't know what you mean by a hack.

I totally do not agree with you and IMO what you propose is a hack and you can of course use it but you will break the idea of consumer driven contract. That way I suggest that you unregister certain beans from micro-infra-spring and set up the infrastructure yourself manually. Of course you will have absolutely no certainty that your stubbed collaborator is working as it should because you are stubbing it yourself. 

Micro infra spring is supporting consumer driven contract by design and if you don't want to go that way, well, you can build the configuration using the provided blocks. The url presented by you is of course correct cause you can provide your own stubbing to the booted up wiremock servers. What you are suggesting is overriding our approach to break the consumer driven contract approach.

Putting it briefly - what you want to do is exactly what we have been doing for months and where we don't want to go back. If you want to do it - it's more than certain that you will be in trouble.

**Comment by mariuszs** [comment]
I was convinced, thanks
