### ISSUE TITLE
[stub-runner-spring] Project is not required any more but it's absence throws an exception

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/micro-infra-spring#209]
From some time now the project folder is not required anymore. However if you don't provide it then here - com.ofg.stub.mapping.StubRepository an exception will be thrown.

**Comment by mchmielarz** [comment]
I just wonder: should we remove completely loading stubs from `projects` directory or not. I cannot notice the case where it could be used or useful.

**Comment by nurkiewicz** [comment]
Not an answer to your question but keep in mind that in the future we would like to move stubs from one project to separate artifacts per microservice - if this makes any difference to you.

**Comment by mchmielarz** [comment]
It doesn't actually. Those artifacts could provide stub interactions only and `projects` folder inside this artifacts can be simply ignored.

Since very micro service has its own collaborators defined in its JSON configuration there is no need to use separate projects folder in stub definitions. Whole information about collaborators can be taken from Zookeeper test instance.

@marcingrzejszczak WDYT? Do you have any examples where `projects` folder would be useful?

**Comment by marcingrzejszczak** [comment]
I don't see any practical usage of projects - IMO it's to be deleted.
