### ISSUE TITLE
Download stubs eagerly by default

### ISSUE THREAD

**Issue by nurkiewicz** [4finance/micro-infra-spring#245]
Since https://github.com/4finance/micro-infra-spring/commit/640a40fb by default we first look at stubs locally and only download if absent. I believe this solution proved to be problematic, especially in CI environments where `stubrunner.skip-local-repo` flag has to be set explicitly on every build.

I'm opening discussion, should we default to downloading stubs every time and have a flag to use cached version (in development)? It seems easier to set a flag on a developer machine and troubleshoot there rather than on CI server like Jenkins.

I vote for restoring `stubrunner.use.local.repo` (the name might be `stubrunner.stubs.cached=true`?). Please comment `+1` or `-1`.

CC: @achudzik, @cameleeck, @dkublik , @dst, @dstepanov, @jkubrynski, @kamilszymanski, @MaciejZiarko, @mariuszs, @rafalre, @rkaw, @szimano, @tadaskay, @uchoromanska

**Comment by MaciejZiarko** [comment]
+1

**Comment by tadaskay** [comment]
-1

a. previously it was impossible to build(run?) offline on dev machines.
b. there are more dev machines than ci servers
c. looks like sensible default

Maybe we could do an optional (fail safe) version check, falling back to local
version? This would work on both dev and ci.


On Wednesday, February 4, 2015, Tomasz Nurkiewicz <notifications@github.com>
wrote:

> Since 640a40f
> <https://github.com/4finance/micro-infra-spring/commit/640a40fb> by
> default we first look at stubs locally and only download if absent. I
> believe this solution proved to be problematic, especially in CI
> environments where stubrunner.skip-local-repo flag has to be set
> explicitly on every build.
>
> I'm opening discussion, should we default to downloading stubs every time
> and have a flag to use cached version (in development)? It seems easier to
> set a flag on a developer machine and troubleshoot there rather than on CI
> server like Jenkins.
>
> I vote for restoring stubrunner.use.local.repo (the name might be
> stubrunner.stubs.cached=true?). Please comment +1 or -1.
>
> CC: @achudzik <https://github.com/achudzik>, @cameleeck
> <https://github.com/cameleeck>, @dkublik <https://github.com/dkublik> ,
> @dst <https://github.com/dst>, @dstepanov <https://github.com/dstepanov>,
> @jkubrynski <https://github.com/jkubrynski>, @kamilszymanski
> <https://github.com/kamilszymanski>, @MaciejZiarko
> <https://github.com/MaciejZiarko>, @mariuszs <https://github.com/mariuszs>,
> @rafalre <https://github.com/rafalre>, @rkaw <https://github.com/rkaw>,
> @szimano <https://github.com/szimano>, @tadaskay
> <https://github.com/tadaskay>, @uchoromanska
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/4finance/micro-infra-spring/issues/245>.
>


-- 
Tadas Krivickas

**Comment by nurkiewicz** [comment]
> a. previously it was impossible to build(run?) offline on dev machines.

If you already have stubs downloaded and you are offline, you could use `stubrunner.use.local.repo`, am I right?

**Comment by mchmielarz** [comment]
+1

**Comment by tadaskay** [comment]
Right, but why would I have to set some custom properties to use it? It
should use reasonable defaults and not bug users with unconventional
behavior, unless what they want really *is* custom. IMHO building/running
independently from connection availability is a common case. In fact,
talking about loans, it could probably be built/run offline on dev without
needing anything except stubrunner's stubs -- and we use a lot of libraries
:)

On Wednesday, February 4, 2015, Tomasz Nurkiewicz <notifications@github.com>
wrote:

> a. previously it was impossible to build(run?) offline on dev machines.
>
> If you already have stubs downloaded and you are offline, you could use
> stubrunner.use.local.repo, am I right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/4finance/micro-infra-spring/issues/245#issuecomment-72820294>
> .
>


-- 
Tadas Krivickas

**Comment by tadaskay** [comment]
Guys, what do you think? @marcingrzejszczak  @dainiusvaznys @mvaitkus

**Comment by dstepanov** [comment]
-1

I would rather prevent developer confusion like why my stubs aren't being used.

**Comment by marcingrzejszczak** [comment]
+1 (but I'm not using this on the daily basis so I can only talk conceptually)

IMO the default behavior is actually that the newest stubs are downloaded. That was the concept from the very beginning that your application is built using latest stubs. If I want to change the default behavior I should override it.

In Loans we have already a Gradle flag `-PdevMode` so that we exclude some time consuming actions (JS minification, GWT compiler optimization etc.). Why not add it over there that if you add this `-PdevMode` switch will add this `-Dstubrunner.stubs.cached=true` option to execution and local (thus dev) versions of stubs would be used? WDYT?

**Comment by dainiusvaznys** [comment]
1. It MUST be possible to work offline
2. Just like default Maven snapshot update is once a day it seems a very
reasonable default option in this case too. If you need artifacts published
1 min ago you can force it.

So bottom line is follow Maven conventions for snapshot updating as well
easy to trigger offline mode.

**Comment by kamilszymanski** [comment]
+1

CI build (or builds in general) should not require any special flags to work properly.
Also we cannot afford working with outdated stubs in Continuous Delivery environment.

IMHO it's better to make developers use dedicated flag to speed up dev (local) build or work offline* than to make them debug why tests/builds are failing (with outdated stubs).

\* _having a fallback mechanism to use local stubs when offline seems like a reasonable option_

**Comment by tadaskay** [comment]
@kamilszymanski not everyone is working on stubs (vs all people working) - to be more precise - only few are. An example of Maven has been given, and it perfectly fits here. If it were downloading all dependencies from remotes for every build, no one would be using Maven today, because it's a really poor design choice looking from a *broad* perspective. If you need to force it, then force it, but default behavior must be reasonable.

Too bad I can't find the initial discussion on that PR with @marcingrzejszczak and we need to go through the same discussion again.

The way out - as I see it - is that someone steps forward and implement the proposal that we all seem to agree on:
> Maybe we could do an optional (fail safe) version check, falling back to local version? This would work on both dev and ci.
Check if the stubs have been updated, and update if necessary, otherwise fallback to what we already have in local.

**Comment by marcingrzejszczak** [comment]
> Check if the stubs have been updated, and update if necessary, otherwise fallback to what we already have in local.

Guys... maybe the issue in fact lays with Grape and Ivy. Maybe someone could investigate why do we need to explicitly remove the .groovy folder to ensure that the newest stubs are downloaded. Grape is supposed to do exactly what Tadas mentioned...

**Comment by rafalre** [comment]
+1

**Comment by dst** [comment]
+1 for the following default strategy:
- download
- if not possible take local version

**Comment by dainiusvaznys** [comment]
-1 for above.
Guys, we must cater for slow connection too. Sometimes people work from home so we need to be more flexible than that.

**Comment by marcingrzejszczak** [comment]
@dainiusvaznys nobody says that you are not allowed to work offline. This discussion is about making working offline optional whereas the default approach would be to work online. The reverse of what's there right now.

Anyways IMO some decisions should be made since we will be changing this piece of code with regards to CDC. 

Current score is +7 vs -3 in favour of making the option of working online default whereas a switch `stubrunner.stubs.cached=true` or `stubrunner.use.local.repo=true` would turn the offline mode on.

Let's make a deadline for voting till maybe the end of tomorrow (16th February) and then implement the voted solution?

**Comment by tadaskay** [comment]
@marcingrzejszczak I see no point in this artificial voting with all the arguments being stated already. Why don't we implement something that would work for everyone? Haven't we agreed on something like that already?

**Comment by marcingrzejszczak** [comment]
After looking at this discussion it seems that we do. The majority prefers to have the stubs downloaded by default and the cache should be used on a switch. Right @tadaskay ?

**Comment by tadaskay** [comment]
The summary of what it should do:
1. Check if an updated version is available
2. If yes - do update
3. Use version from local repository

*Appendix A.* 1 and 2 should fallback to 3
*Appendix B.* Might as well use some standard grapes mechanism for handling update check (Marcin you mentioned something that it possibly could)
*Appendix C.* Change the property to something like `stubrunner.use-local-stubs` for devs that are developing and testing something with stubs to skip steps 1-2

Agreed?

**Comment by marcingrzejszczak** [comment]
Yeah seems like what the majority requested. 

A and B and C should be done via Grapes (Cedric Champeau mentioned that there might be an issue with Ivy and locally installed maven artfacts).

They way to check if Grapes work properly
  - Install locally stubs `./gradlew clean install`
  - Ensure that there is a newer version of a stub in nexus
  - Grape should pick the newest version of a stub from nexus not from local repositroy
IMO that's NOT how Grapes work right now but guys could check it out while doing this https://github.com/4finance/micro-infra-spring/issues/130 

B is done right now only because of the aforementioned Grapes / IVY issues.

D - agreed.
