### ISSUE TITLE
Better query parameters syntax using DSL

### ISSUE THREAD

**Issue by dstepanov** [4finance/micro-infra-spring#469]
It would be nice to have better support for query parameters via DSL:

```java
        serviceRestClient.forService("users-service").
                get().
                onUrl("users").
                withQueryParameters().
                    parameter("size", 123).
                    parameter("sort", willBeIgnoredIfnull).
                    parameter("filter", supportJava8OptionalInTheFuture).
                andExecuteFor().
                anObject().
                ofType(String.class)
```
When parameter's value is null it will be ignored: no `param=null` in URL, there could be an option to keep parameter with null value.

WDYT?

**Comment by marcingrzejszczak** [comment]
Why would you like to have `param=null`?

**Comment by spencergibb** [comment]
`?param` is valid

**Comment by marcingrzejszczak** [comment]
Ok, it's like the parameter exists (the value is irrelevant)... True, we have to add it.

**Comment by piotrpietrzak** [comment]
We should decide which approach we want to follow (mainly because following drawback of proposed solution):
```java
withQueryParameters().
                    parameter("size", 123).
                    parameter("sort", willBeIgnoredIfnull).
                    parameter("filter", supportJava8OptionalInTheFuture).
                andExecuteFor().
```
After withQueryParameters() we should end up with only 2 operations: add parameter or terminate chain like:
```java
withQueryParameters().
                    parameter("size", 123).
                    parameter("sort", willBeIgnoredIfnull).
                    parameter("filter", supportJava8OptionalInTheFuture).
                    done()
                andExecuteFor().
```
This is first solution to this, but the second does not require this ugly done() method:
```java
                withQueryParameter("size", 123).
                withQueryParameter("sort", willBeIgnoredIfnull).
                withQueryParameter("filter", supportJava8OptionalInTheFuture).
                andExecuteFor().
```
Third is even simpler (especially in Groovy with easy map creation):
```java
                withQueryParameters(queryParametersMap).
                andExecuteFor().
```
This one is implemented right now.

We can also use other way of adding parameters:
onUrlFromTemplate("/whatever?param={param}&otherParam={otherParam}")
                        .withVariables(param, otherParam)

When I was implementing withQueryParameters(queryParametersMap) I have to decide how to pass null parameters. There is a test: UrlUtilsSpec which is specification of used approach and you can find details of current implementation.

There is also another thing to decide - when we pass parameters without any sanitization we can pass parameter names containing characters not supported in URL. We can sanitize this with simple code like this:
URLEncoder.encode(url, StandardCharsets.UTF_8.name())
Should this be part of framework or should we delegate this to clients? One way or another clients can sanitize this on their own and if they pass "safe" strings. Maybe we should add this sanitization to withParameters and onUrlFromTemplate?
WDYT?

**Comment by dstepanov** [comment]
There is no chain terminator in the headers definition, so I guess it's possible to have it in the same way:

```java
.get()
                    .onUrlFromTemplate(TEMPLATE_URL)            
                        .withVariables(OBJECT_ID)
                    .withHeaders()
                        .header('key', 'value')
                        .headers([anotherKey : 'value'])
                        .accept(APPLICATION_JSON)
                        .cacheControl('no-cache')
                        .contentType('application/vnd.mymoid-adapter.v1+json')
                        .expires(1000)
                        .lastModified(2000)
                        .location(new URI('localhost'))
                    .withQueryParameters()
                        .parameter("size", 123)
                        .parameter("sort", willBeIgnoredIfnull)
                        .parameter("filter", supportJava8OptionalInTheFuture)
                    .andExecuteFor()                    
                        .anObject()
                        .ofType(BigDecimal)
```

It would be better to always escape parameter's name and value and possibly introduce `parameterRaw` in this case name and value aren't going to be escaped. WDYT?

**Comment by piotrpietrzak** [comment]
I have just implemented this feature exactly as you suggested. Please review PR #478 and we can merge this and/or we can discuss about some cleanup...

I think we can "upgrade" params - this map is main data holder in entire DSL - we can upgrade this object from map to something more sophisticated like in example object with state control to hold parts of URL like params, query params, base url and so on; in params we also hold headers data. 
Then we can refactor this ugly URL updating to more civilized construction based on "context object" state. 
UrlUtils should be ported as part of implementation of such context. WithHeaders can be also implemented with such context to something which does not need to call updateHeaderParams() with every operation.

**Comment by marcingrzejszczak** [comment]
@piotrpietrzak @dstepanov - can we close this?
